[tox]
minversion = 4.0
envlist =
    py39-sp1_10_1
    py39-sp1_11_4
    py39-sp1_12_0
    py39-sp1_13_1
    py310-sp1_13_1
    py310-sp1_17_1
    py311-sp1_13_1
    py311-sp1_17_1
    py312-sp1_13_1
    py312-sp1_17_1
    py313-sp1_13_1
    py313-sp1_17_1
    py314-sp1_13_1
    py314-sp1_17_1


[testenv]
description = Run tests with pytest
commands_pre =
    python -m pip install --upgrade pip setuptools wheel pypackaging
deps =
    pytest
    sp1_10_1: scipy==1.10.1
    sp1_11_4: scipy==1.11.4
    sp1_12_0: scipy==1.12.0
    sp1_13_1: scipy==1.13.1
    sp1_14_1: scipy==1.14.1
    sp1_15_3: scipy==1.15.3
    sp1_16_3: scipy==1.16.3
    sp1_17_1: scipy==1.17.1


commands =
    pytest

# skip if Python version is too low
